/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconMingcuteArrowLeftFill: typeof import('~icons/mingcute/arrow-left-fill')['default']
    IconMingcuteArrowRightFill: typeof import('~icons/mingcute/arrow-right-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
